### ISSUE TITLE
No error printed if command line execution fails

### ISSUE THREAD

**Issue by snowhork** [hirosassa/bqiam#18]
To add bigquery execution role, we use `gcloud` command in this command.

If `gcloud` command exits by error code=1, no errors are printed.

**Comment by hirosassa** [comment]
@snowhork Thanks for reporting! Do you have examples for reproducing?

**Comment by snowhork** [comment]
@hirosassa 
For example, If SA doesn't exist, gcloud command exits 1. But, error messages by gcloud are not printed.

```
$ ./bqiam permit dataset READER -p myproject -u hoge@non.exists.com -d piyo

failed to permit: failed to update policy bindings to grant hoge@non.exists.com roles/bigquery.jobUser: error: exit status 1
```

If we use gcloud command, we can see error messages.

```
$ gcloud projects add-iam-policy-binding myproject --member serviceAccount:hoge@non.exists.com --role roles/bigquery.jobUser

ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Service account hoge@non.exists.com does not exist.
```
